### ISSUE TITLE
Wrong Hijri Date

### ISSUE THREAD

**Issue by mehdico** [shahednasser/quran-extension#11]
Today is 19/8/2021 and 10 Muḥarram 1443 in IRDT or UTC +4:30, but the extension displays **11** Muḥarram 1443.
Maybe add a setting to fix the day of the month by +1 & -1 options, or update Hijri date from an online time provider.

**Comment by shahednasser** [comment]
Thank you @mehdico for the feedback. A previous version of this extension was using an online time provider, however, the same problem occurred as the Hijri date was different.

This is mainly due to different regions. For example, here in Lebanon, it's 11 Muharram. So, I think I need to find another way to get the date based on the user's location.

If you have any suggestions please let me know as well!
